spring:
  datasource:
    db1:
      url: jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
      username: sa
      password:
    db2:
      url: jdbc:h2:mem:db2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
      username: sa
      password:
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jpa:
    defer-datasource-initialization: true
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.example.login.model

logging:
  level:
    org.h2: DEBUG
    com.example.login: DEBUG
